"""
Django settings for Booking_Backend project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-vl2x+yw2_%l&o@cas6awz-d0w9%5#^$0b9y@u_zjrctws3zojx'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition
INSTALLED_APPS = [
    'cloudinary',
    'cloudinary_storage',
    "corsheaders",
    'rest_framework',
    'rest_framework.authtoken',
    'Room_Booking',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Booking_Backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Booking_Backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'hotelbooking',
        'USER': 'root',
        'PASSWORD': '1144',
        'HOST': 'localhost',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/
import os
STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

AUTH_USER_MODEL = 'Room_Booking.User'   # ✅
AUTHENTICATION_BACKENDS = ["Room_Booking.auth_backend.EmailBackend"]


REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES":[
        "rest_framework.authentication.BasicAuthentication",
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.TokenAuthentication"
    ],
    
}

CSRF_TRUSTED_ORIGINS = [
    'https://booking-app-backend-gqr0.onrender.com',
    'https://booking-app-nine-ruby.vercel.app',
]
CORS_ALLOWED_ORIGINS = [
    # "http://127.0.0.1:5173",
    # "http://localhost:5173",
    "https://booking-app-nine-ruby.vercel.app"
]
CORS_ALLOW_CREDENTIALS = True
CORS_EXPOSE_HEADERS = [
    "Content-Type",
    "Authorization",
]
ROOT_URLCONF = 'Booking_Backend.urls'
import os

# For offline serving:
# MEDIA_URL = '/media/'  # URL path for media files
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  # Directory to store media files

import cloudinary
import cloudinary.api
import cloudinary.uploader

# Cloudinary configuration
cloudinary.config(
    cloud_name="dxbm4jutk",
    api_key="154477864673916",
    api_secret="JepRjLTqD_kDGP6XN-jjYFjKK3U",
    secure=True,
)

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': 'dxbm4jutk',
    'API_KEY': '154477864673916',
    'API_SECRET': 'JepRjLTqD_kDGP6XN-jjYFjKK3U',
}

DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'



# import dj_database_url
# database_url = os.environ.get("DATABASE_URL")
# DATABASES['default'] = dj_database_url.parse(database_url)


# DEBUG = os.environ.get("DEBUG","False").lower() == "true"
# ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS").split(" ")
# SECRET_KEY = os.environ.get("SECRET_KEY")